name: b
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Apply Patches
        continue-on-error: true
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
          ./gradlew applyPatches
          tar -czf src.tar.gz starlivht-*
      - uses: actions/upload-artifact@v2
        with:
          name: 727
          path: src.tar.gz
